name: coolstar-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - isort
  - mypy
  - flake8
  - black
  - python=3.9
  - pytorch
  - jupyter
  - seaborn
  - pandas
  - numpy
  - matplotlib
  - keras
  - pre-commit
  - scikit-learn
  - pylint
  - pytables
  - pip:
      - skfeature-chappers
      - scikit-learn
      - imblearn
