version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Create env
          command: |
            conda install -c anaconda make
            make create_env
            source coolstar-dev activate
            make install
      - run:
          name: Run lint
          command: |
            source coolstar-dev activate
            make lint
