version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9.13
    steps:
      - checkout
      - run:
          name: Create env
          command: |
            make create_env
            source coolstar-dev activate
            make install
      - run:
          name: Run lint
          command: |
            source coolstar-dev activate
            make lint

