version: 2.1
jobs:
  build:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Create env
          command: |
            conda install -c anaconda make
            make create_env
            conda init bash
            source ~/.bashrc
            conda activate coolstar-dev
            make install
      - run:
          name: Run lint
          command: |
            conda activate coolstar-dev
            make lint
