data_dir: data
plots_dir: plots
fp_june20: spectral_templates_data_version_june20.h5
fp_july15: spectral_templates_data_version_july15.h5
fp_july26: spectral_templates_data_version_jul26.h5
singles_key: singles
binaries_key: binaries
wavegrid_key: wavegrid
spectral_type_col: spectral_type
binary_drop_cols: ["primary_type", "secondary_type"]
binary_rename_col: system_type
single_drop_cols: ["object_name"]
target_col: single

singles_flux_key: singles_flux
binaries_flux_key: binaries_flux
singles_noise_key: singles_noise
binaries_noise_key: binaries_noise
singles_diff_key: singles_difference_spectrum
binaries_diff_key: binaries_difference_spectrum
merge_key: "object_name"
noise_suffix: _noise
diff_suffix: _diff
primary_type_col: primary_type
secondary_type_col: secondary_type
zero_div_offset: 1.0e-50
chisq_rescale: 1.0e-5
noise_scale: 5
seaborn_style: whitegrid
seaborn_palette: hls
seaborn_figsize: [16, 6]
savefig.dpi: 300
figure.dpi: 300
test_size: 0.2

snr_ranges: [[0, 3], [3, 5], [5, 10], [10, 20], [20, 1000]]
